### ISSUE TITLE
Could not find IPC

### ISSUE THREAD

**Issue by arukanoido** [Snazzah/SublimeDiscordRP#1]
Installed as a sublime text 3 package in AppData\Roaming\Sublime Text 3\Packages\User
When I launch I get this error message:
Could not find IPC. Please open Discord and run "DiscordRichPresence: Connect to Discord"

Am I missing a dependency or do I have to enable something in Discord?

**Comment by Snazzah** [comment]
Can you copy and paste what Sublime console (`Ctrl+\``) says? Also find a
line in the Discord console (`Ctrl+Shift+I`) where it states opening an IPC
and paste its path please.

**Comment by arukanoido** [comment]
###Sublime
```
[DiscordRP] Loaded
[DiscordRP] Starting IPC with client id 389368374645227520
[DiscordRP] Testing pipe /tmp/discord-ipc-0
[DiscordRP] Testing pipe /tmp/discord-ipc-1
[DiscordRP] Testing pipe /tmp/discord-ipc-2
[DiscordRP] Testing pipe /tmp/discord-ipc-3
[DiscordRP] Testing pipe /tmp/discord-ipc-4
[DiscordRP] Testing pipe /tmp/discord-ipc-5
[DiscordRP] Testing pipe /tmp/discord-ipc-6
[DiscordRP] Testing pipe /tmp/discord-ipc-7
[DiscordRP] Testing pipe /tmp/discord-ipc-8
[DiscordRP] Testing pipe /tmp/discord-ipc-9
[DiscordRP] Testing pipe /tmp/discord-ipc-10
error: DiscordRP

Could not find IPC. Please open Discord and run "DiscordRichPresence: Connect to Discord"
```

###Discord
`[RPCServer:IPC] Starting on \\?\pipe\discord-ipc-0`

**Comment by PointyDev** [comment]
Can second the above.

![](https://pointy.needs-to-s.top/b53075.png)
![](https://pointy.needs-to-s.top/ce9bd1.png)

**Comment by Snazzah** [comment]
I think I know the problem here. I'll make a fix for it later on.
