### ISSUE TITLE
ST stops responding when using Goto Anything

### ISSUE THREAD

**Issue by lkhrs** [Snazzah/SublimeDiscordRP#109]
While using Goto Anything with SublimeDiscordRP installed, Sublime Text stops responding indefinitely.

macOS 13.5.1
Sublime Text 4152

Steps to reproduce:
1. Install SublimeDiscordRP
2. Open Goto Anything
3. Use the cursor keys to rapidly move through the file list, or search for a term that opens multiple files

**Comment by r3k4** [comment]
same here..
using **ubuntu 24.04**, tried **ubuntu 23.10** as well.
**sublimetext version 4169**

seems like this package scanned everything when we press goto anything button..
it would be nice if scan file is disabled when we press this combination button.

**Comment by jaraco** [comment]
I encountered this issue as well. I spent hours troubleshooting the issue in https://github.com/sublimehq/sublime_text/issues/6459 and other places. There you can find screenshots of the issue happening. I won't be using the package until this bug is fixed.

**Comment by TerminalFi** [comment]
FWIW, I do not use this plugin. However, the issue likely lies in these lines

https://github.com/Snazzah/SublimeDiscordRP/blob/3ce66fc29a3426c683520444a786989633074bca/drp.py#L460-L461

It triggers every time the file changes in goto anything, It should probably be updated to be more like

```
    def on_load_async(self, view):
        if view.sheet().is_transient():
            return
        handle_activity(view)
```

**Comment by FichteFoll** [comment]
In fact, we should probably only listen to `on_activated` and not handle `on_load` at all.

**Comment by jaraco** [comment]
Confirmed that this does indeed address the issue. Thanks!
