### ISSUE TITLE
Send Activity failed.

### ISSUE THREAD

**Issue by DoctorVWA** [Snazzah/SublimeDiscordRP#12]
sometimes when I save the file this error appers:
![image](https://user-images.githubusercontent.com/17722403/34017655-bdbf4b28-e10d-11e7-8b38-454590883172.png)

**Comment by FichteFoll** [comment]
391ff75debcc2da628872c4603785d445f53d3f3 introduced automatic reconnects. Let me know if this "solves" the problem for you.
