### ISSUE TITLE
Automatic reconnect, less intrusive errors

### ISSUE THREAD

**Issue by DuendeInexistente** [Snazzah/SublimeDiscordRP#16]
In the time I've used this plugin, I've found it consistently annoying to have [errors popping up constantly](https://files.catbox.moe/p5hkfm.png)  because of broken pipes and whatnot, and don't really think it's necessary that they appear as they do at all.

So my suggestion in this issue is:

 1. Make the errors appear as messages on the status bar and be logged to the console. This way they'll still be visible (Maybe add a pair of newlines above and below, or some distinctive character to make it easier to find) while not completely interrupting one's workflow
 2. And more important, *reconnect silently in the background*, There really is no need that I am interrupted and then have to connect it manually again. Ideally, add a setting to delay retries (15 secs by default sounds good to me) so that people can tweak that to their needs.

**Comment by FichteFoll** [comment]
Just out of curiosity, how often does this happen to you? Which OS are you on and what discord version do you use? The only times when I have been disconnected from the discord client have been when I closed it.

**Comment by DuendeInexistente** [comment]
Xubuntu 17, the lastest of both, and several because of my shaky internet
connexion.
