### ISSUE TITLE
Licensing for IPC code

### ISSUE THREAD

**Issue by BlindJoker** [Snazzah/SublimeDiscordRP#21]
Hey there.

Would it be possible to add licensing information to the `discord_ipc` module, so it can be used by other projects?

**Comment by FichteFoll** [comment]
Uh, sure thing. Technically I wrote all of the `discrod_ipc` module and I prefer the ISC/MIT, but I'd need @Snazzah's consent on this too. Well, I'd need it for the whole repo, which would be the proper way.

I'm just curious though, what do you intend to use it for?

**Comment by Snazzah** [comment]
Adding a MIT License is fine

**Comment by FichteFoll** [comment]
Oh, and @gwenzek's too, I guess, unless you wish to decline having your name included for whatever reason. I think @coderobe's cotributions are technically minimal, but we should ask anyway.

(That's what you get for not checking for a license earlier. 😑)

**Comment by Snazzah** [comment]
yeah sure

**Comment by BlindJoker** [comment]
Intending to use it for a Quod Libet (music player) plugin. Once I get everything working, I'll be open sourcing it too.

**Comment by gwenzek** [comment]
Thanks for including me in the discussion. But given the modest scope of my contribution, I'd rather not be mentioned.

**Comment by FichteFoll** [comment]
Added in 202daec50c11357ca1d2cbe3cada496e7c319269.
