### ISSUE TITLE
Settings for SublimeDiscordRP [Enhancement]

### ISSUE THREAD

**Issue by ThaumicTom** [Snazzah/SublimeDiscordRP#22]
Hej,
I wish settings these options for SublimeDiscordRP:
- Dis-/Enable the file size on the Presence
- Dis-/Enable name of the file
- Dis-/Enable the view of the file's extension
- Add a custom small Picture

**Comment by FichteFoll** [comment]
>- Dis-/Enable the file size on the Presence
>- Dis-/Enable name of the file

You can configure the text that is sent to Discord freely in the settings, using templating variables. Everything should be explained through comments in the default settings file.

>- Dis-/Enable the view of the file's extension

I'm not exactly sure what you mean by that. Do you mean the syntax name that appears when hovering the small icon?

>- Add a custom small Picture

Unfortnately, this is not possible through the API. If you want an icon added for a certain file type, feel free to open an issue with the image though, so we can upload it for our "app" to choose from.

**Comment by ThaumicTom** [comment]
(As quoting does not work on here I will have to tell you, where I am at)
For the first one: I opened the wrong settings while, were nothing was. My bad.
For the second one: I mean the small Icon, yes.
For the third one: Understandable, thanks!

**Comment by FichteFoll** [comment]
You can disable the small icon entirely, if that helps.

**Comment by ThaumicTom** [comment]
I have looked up once more, there is no text in the settings file.
