### ISSUE TITLE
Changing Icon Set

### ISSUE THREAD

**Issue by Shugabuga** [Snazzah/SublimeDiscordRP#24]
I am trying to replace the default set of icons with my own (to match a custom Sublime icon). I tried creating a new application with Discord, enabled RPC, and uploaded my icons. I then swapped out the keys in the fork. However, the icon names seem to not be correct. Here is what I uploaded as assets:

```
c
Small

c
Large

cpp
Small

cpp
Large

crystal
Small

crystal
Large

cs
Small

cs
Large

css
Small

css
Large

d
Small

d
Large

elixir
Small

elixir
Large

extra
Small

extra
Large

go
Small

go
Large

html
Small

html
Large

java
Small

java
Large

javascript
Small

javascript
Large

json
Small

json
Large

lua
Small

lua
Large

markdown
Small

markdown
Large

php
Small

php
Large

python
Small

python
Large

ruby
Small

ruby
Large

rust
Small

rust
Large

sh
Small

sh
Large

sublime3
Large

sublime3
Small

typescript
Small

typescript
Large
```

What is the proper way to do so?

**Comment by FichteFoll** [comment]
The language is prefixed with `lang-` in the code: 

https://github.com/Snazzah/SublimeDiscordRP/blob/cd6579588f086f29d6437844407188a8e2cb06e7/drp.py#L76

**Comment by Snazzah** [comment]
This is not conventional for usage of Discord Rich Presence.

**Comment by Shugabuga** [comment]
@FichteFoll Thank you. That's exactly what I was looking for.
