### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Mdstumpfy123** [Snazzah/SublimeDiscordRP#25]
How do I setup this?

I added the files to a folder in my Packages and it isn't working.

**Comment by FichteFoll** [comment]
Run the "Discord Rich Presence: Connect to Discord" command. Also check the settings through "Preferences: Discord Rich Presence Settings".

**Comment by Mdstumpfy123** [comment]
This is all I see when I search DISCORD
https://did-you-know-that-the-last.letters-of-the-alphabet-are.xyz/htN2FerN.png
(this is a picture link)

**Comment by FichteFoll** [comment]
If you installed the package manually, it needs to be stored in a folder named "Discord Rich Presence".

I assume you did that because of the current Package Control issues?

**Comment by Mdstumpfy123** [comment]
Ok so I named the folder that and clicked connect and it isn't beaming to my discord

**Comment by Mdstumpfy123** [comment]
Never mind I got it working.
