### ISSUE TITLE
Skript

### ISSUE THREAD

**Issue by Hakim567** [Snazzah/SublimeDiscordRP#26]
Hello can you add a new icon to .sk files?
https://imgur.com/a/Z5i7E

**Comment by Hakim567** [comment]
Why no update :(

**Comment by Snazzah** [comment]
1. The icon doesn't really look good when in Discord Rich Presence since it's just "Skript" in a bunch of fonts.
2. Space for icons is limited in Discord, so i'm using them for some of the at least somewhat popular coding languages
