### ISSUE TITLE
Read messages sent from the Discord client and check for errors

### ISSUE THREAD

**Issue by FichteFoll** [Snazzah/SublimeDiscordRP#27]
Would help immensely with logging and debugging.

I don't know if the client sends messages by itself (by default, without registering any events) or whether it only replies. Either way, it appears that the reply will have the same `nonce` attribute as the request, so we can just discard any other messages we receive. We definitely need a timeout, though.

Alternatively, we could create a new thread that only listens for received messages and logs them with the appropriate logging level. We probably can't attribute replies to requests properly, but I don't think we need to.

See also #23.

**Comment by Snazzah** [comment]
I think it should use `send_recv` instead of just `send` to parse any errors that come into sending the presence.

**Comment by FichteFoll** [comment]
According to the [hard mode documentation](https://github.com/discordapp/discord-rpc/blob/master/documentation/hard-mode.md#notes):

> IPC will echo back every command you send as a response. Use this as a lock-step feature to avoid flooding messages. Can be used to validate messages such as the Presence or Subscribes.

Since we don't subscribe to events, I'll just use send_recv for all messages with a reasonable timeout.

**Comment by FichteFoll** [comment]
I tried implementing a timeout, but asynchronous I/O on Windows is a nightmare and [this SO answer](https://stackoverflow.com/a/36190409/1327727) using `ctypes` was the closest solution I could find. I decided that this is just not worth the hassle for most cases and just run everything in the async thread now to ensure the UI doesn't freeze.
