### ISSUE TITLE
Discord status not changing to Sublime Text after update

### ISSUE THREAD

**Issue by mtetik98** [Snazzah/SublimeDiscordRP#28]
As the title says, whenever I open discord and then open sublime text 3, status doesn't appear. It worked great yesterday..

**Comment by FichteFoll** [comment]
What's your OS and please post a the console log after setting the level to "DEBUG" in the settings.

**Comment by mtetik98** [comment]
![image](https://user-images.githubusercontent.com/35567823/38614640-16333044-3d8e-11e8-8363-c5ad28cff6b9.png)

My current OS : Windows 8.1
