### ISSUE TITLE
Lookup syntax friendly name rather than using a hardcoded list

### ISSUE THREAD

**Issue by keith-hall** [Snazzah/SublimeDiscordRP#3]
Hi,

Thanks for this plugin! I have one idea which could make it even better - rather than [hardcode a list of file extensions and a mapping to their friendly names](https://github.com/Snazzah/SublimeDiscordRP/blob/53991d46ce679bd191fb5165c350833a7b8c806a/DiscordRichPresence.py#L28-L81), it'd be cool if you'd take the `view.settings().get('syntax', None)` and parse that file with `pyyaml` to get the `name` key directly from the syntax definition, if it is present. If it isn't, maybe just use the base file name of the `.sublime-syntax`/`.tmLanguage` file? This would allow you to support all third party syntaxes without any extra work, without any false mappings when one file extension could relate to multiple syntaxes.

**Comment by Snazzah** [comment]
Fixed since [`66ec8ac`](https://github.com/Snazzah/SublimeDiscordRP/commit/66ec8ac743f9827fb1193798c8f9c2befb0b22a7).

**Comment by FichteFoll** [comment]
https://github.com/Snazzah/SublimeDiscordRP/commit/e7e9aaa6170dc558f4b13d04389db49630ecbc42 rather.
