### ISSUE TITLE
Time elapsed counter inaccurate.

### ISSUE THREAD

**Issue by SteelTitanium** [Snazzah/SublimeDiscordRP#34]
Right after saving the file, it will show over 3 hours has elapsed on the profile.

**Comment by FichteFoll** [comment]
Currently, the time elapsed counter points at the time you opened Sublime Text.

Would you suggest to base the time on when you started working on the current project (and whether that should be remembered when you switch) or when you opened the current file? I could make it configurable, but the point is that it's hard to make out a certain point in time you would want to display in discord.

**Comment by SteelTitanium** [comment]
I think it should be based on the former.

**Comment by michaelowens** [comment]
It seems like it currently does not respect timezones resulting in incorrect times, thus for me it's ~13 hours behind it seems.

I fixed it by changing the `start_time` line to:
`start_time = mktime(time.localtime())`

**Comment by FichteFoll** [comment]
The original issue hasn't been addressed.

**Comment by TorchedSammy** [comment]
what would be the reason for this still being open?
