### ISSUE TITLE
Unable to Connect Discord Client

### ISSUE THREAD

**Issue by dytra** [Snazzah/SublimeDiscordRP#36]
Hi it's my first time trying this plugin, but somehow it shows error message that it couldn't connect to my discord client. but I already installed and ran the discord client on my machine

```
[DiscordRP] Unable to connect to Discord client.

Please verify that it is running. Run 'Discord Rich Presence: Connect to Discord' to try again.
```

 I'm running Ubuntu 18.04
Is it because I'm running linux ?

**Comment by FichteFoll** [comment]
Linux is supported (and in fact I developed it on Linux).

Can you check the ST console for other errors or warnings? Also enable debug logging for DiscordRP via its settings file.

**Comment by dytra** [comment]
Fixed
I found that this problem caused by installing Discord from Ubuntu App Center 
I reinstall discord using terminal and this error doesn't show up again

**Comment by FichteFoll** [comment]
Interesting. Maybe the flatpak version (I assume it's flatpak) installs discord at a different location or isolates it in some way so that the default IPC pipe paths don't work. That said, I'm not exactly interested in pursuing this personally.

**Comment by FichteFoll** [comment]
See #38 for details, btw.
