### ISSUE TITLE
Not sending start_state setting

### ISSUE THREAD

**Issue by ColorsASD** [Snazzah/SublimeDiscordRP#37]
<img src="https://cdn.discordapp.com/attachments/448912599837573130/548975145390440448/Discord.png">
Please fix.

**Comment by ColorsASD** [comment]
[](https://cdn.discordapp.com/attachments/448912599837573130/548975145390440448/Discord.png)

**Comment by FichteFoll** [comment]
Fix what exactly?

**Comment by ColorsASD** [comment]
```
    // The state message when Sublime Text (or the plugin) starts. (NOT FORMATTED)
    "start_state": "Just launched",
```
