### ISSUE TITLE
SublimeDiscordRP doesn't work with Snap installed Sublime Text and Discord

### ISSUE THREAD

**Issue by jkelol111** [Snazzah/SublimeDiscordRP#38]
**OS**: Ubuntu 18.04 (KDE neon)

**Sublime Text version**: 3.2 Build 3200 (installed from Snapcraft)

**Issue**:

If Sublime Text and Discord is installed from the Snapcraft, SublimeDiscordRP errors out during connect, saying it cannot connect to the Discord client.

**Comment by FichteFoll** [comment]
Can you find out where discord installed as a snap creates its FIFO pipes?

**Comment by jkelol111** [comment]
Sorry for not getting back earlier, here's the command output:

`jkelol111@neon:~/Documents$ ls -l /proc/2588/fd
total 0
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 0 -> /dev/null
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 1 -> /home/jkelol111/.xsession-errors
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 10 -> /snap/discord/93/usr/share/discord/chrome_200_percent.pak
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 102 -> '/dev/shm/.org.chromium.Chromium.ZoymgU (deleted)'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 107 -> /usr/share/fonts/truetype/freefont/FreeMono.ttf
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 11 -> /snap/discord/93/usr/share/discord/locales/en-US.pak
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 111 -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 113 -> '/dev/shm/.org.chromium.Chromium.hexCh0 (deleted)'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 12 -> /snap/discord/93/usr/share/discord/resources.pak
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 13 -> /dev/urandom
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 14 -> 'pipe:[54746]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 15 -> 'socket:[55372]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 16 -> /snap/discord/93/usr/share/discord/v8_context_snapshot.bin
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 17 -> /snap/discord/93/usr/share/discord/natives_blob.bin
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 18 -> 'pipe:[54746]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 19 -> 'pipe:[54747]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 2 -> /home/jkelol111/.xsession-errors
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 20 -> 'pipe:[54747]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 21 -> 'anon_inode:[eventfd]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 22 -> 'anon_inode:[eventpoll]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 23 -> 'socket:[54744]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 24 -> 'socket:[54758]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 25 -> 'anon_inode:[eventpoll]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 26 -> 'socket:[55378]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 27 -> 'socket:[55379]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 28 -> 'pipe:[55380]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 29 -> 'pipe:[55380]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 3 -> 'anon_inode:[eventpoll]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 30 -> 'anon_inode:[eventpoll]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 31 -> 'socket:[54752]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 32 -> 'socket:[54753]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 33 -> 'pipe:[54754]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 34 -> 'pipe:[54754]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 35 -> '/dev/shm/.org.chromium.Chromium.7QSuY7 (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 36 -> 'anon_inode:[eventpoll]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 37 -> 'pipe:[54766]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 38 -> '/dev/shm/.org.chromium.Chromium.VjyJ77 (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 39 -> '/dev/shm/.org.chromium.Chromium.rj9VU4 (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 4 -> 'socket:[54392]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 40 -> /usr/share/fonts/truetype/msttcorefonts/Arial.ttf
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 41 -> 'pipe:[54766]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 42 -> /snap/discord/93/usr/share/discord/resources/electron.asar
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 43 -> /home/jkelol111/snap/discord/93/.config/discord/0.0.9/modules/discord_desktop_core/core.asar
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 44 -> 'anon_inode:[eventfd]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 45 -> /dev/urandom
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 46 -> 'anon_inode:[eventpoll]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 47 -> 'pipe:[55467]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 48 -> 'pipe:[55467]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 49 -> 'anon_inode:[eventpoll]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 5 -> /dev/urandom
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 50 -> 'socket:[55468]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 51 -> 'socket:[55469]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 52 -> 'pipe:[55470]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 53 -> 'pipe:[55470]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 54 -> 'pipe:[55471]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 55 -> 'pipe:[55471]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 56 -> 'socket:[55475]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 57 -> 'anon_inode:[eventfd]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 58 -> 'anon_inode:[eventfd]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 59 -> 'socket:[55476]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 6 -> /snap/discord/93/usr/share/discord/icudtl.dat
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 60 -> 'anon_inode:[eventpoll]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 61 -> 'pipe:[55479]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 62 -> 'pipe:[55479]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 63 -> 'anon_inode:[eventfd]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 64 -> 'socket:[55480]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 65 -> 'socket:[55482]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 66 -> 'anon_inode:[eventpoll]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 69 -> 'socket:[55569]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 7 -> /snap/discord/93/usr/share/discord/v8_context_snapshot.bin
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 70 -> 'pipe:[54769]'
l-wx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 71 -> 'pipe:[54769]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 72 -> 'anon_inode:[eventfd]'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 73 -> /dev/null
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 74 -> /usr/share/fonts/truetype/msttcorefonts/Times_New_Roman.ttf
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 75 -> 'socket:[55568]'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 78 -> '/dev/shm/.org.chromium.Chromium.Rzeq33 (deleted)'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 8 -> /snap/discord/93/usr/share/discord/natives_blob.bin
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 80 -> '/dev/shm/.org.chromium.Chromium.n9A0r8 (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 84 -> '/dev/shm/.org.chromium.Chromium.bbSBYH (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 85 -> '/dev/shm/.org.chromium.Chromium.dnFyRI (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 86 -> '/dev/shm/.org.chromium.Chromium.NglyKJ (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 87 -> '/dev/shm/.org.chromium.Chromium.XmCEQc (deleted)'
lrwx------ 1 jkelol111 jkelol111 64 Mac  29 13:08 88 -> '/dev/shm/.org.chromium.Chromium.5sEybO (deleted)'
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 89 -> /usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 9 -> /snap/discord/93/usr/share/discord/chrome_100_percent.pak
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 94 -> /usr/share/fonts/truetype/msttcorefonts/Arial_Bold.ttf
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 96 -> /usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Bold.ttf
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 97 -> /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf
lr-x------ 1 jkelol111 jkelol111 64 Mac  29 13:08 98 -> /usr/share/fonts/truetype/noto/NotoSansSymbols2-Regular.ttf`

**Comment by FichteFoll** [comment]
Unfortunately that doesn't reveal the paths, but I found https://github.com/discordjs/RPC/issues/36 and will add a fallback to that path.

**Comment by FichteFoll** [comment]
I submitted a fix and a new release. Please test whether it works now, and if it doesn't, please set `"log_level": "DEBUG"` in your settings and provide the console output.
