### ISSUE TITLE
Cannot edit settings.

### ISSUE THREAD

**Issue by AdxmGG** [Snazzah/SublimeDiscordRP#39]
I want to edit the settings so it doesnt show the project name, but its not letting me edit the settings file.

**Comment by FichteFoll** [comment]
Please elaborate on your steps, what you expect and what happens instead.

**Comment by adammcgrogan** [comment]
So I do "CTRL, SHIFT, P" and go to the Discord Rich Presence settings, I then go to ""details": "Editing {file} for Project {project}"," and try to remove "for Project {project}", because I don't want the project to show up. But it will not let me edit this, (just doesnt let me edit anything)

**Comment by FichteFoll** [comment]
You need to copy the keys you want to modify over to the right side and edit them there. The left panel is read-only.

This is exactly the same procedure as for the normal ST preferences.
