### ISSUE TITLE
can't connect to discord

### ISSUE THREAD

**Issue by Dragonblitz10** [Snazzah/SublimeDiscordRP#43]
Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 13] Permission denied: '\\\\?\\pipe\\discord-ipc-0'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 13] Permission denied: '\\\\?\\pipe\\discord-ipc-0'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 13] Permission denied: '\\\\?\\pipe\\discord-ipc-0'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 13] Permission denied: '\\\\?\\pipe\\discord-ipc-0'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-

discord console:
[RPCServer:IPC] Starting on \\?\pipe\discord-ipc-0

**Comment by Dragonblitz10** [comment]
closed, running in admin fixes

**Comment by FichteFoll** [comment]
Did you run Discord as admin as well? It shouldn't require admin privileges.

**Comment by Dragonblitz10** [comment]
the issue was i had discord running in admin
