### ISSUE TITLE
Add V language support

### ISSUE THREAD

**Issue by PiggyPiglet** [Snazzah/SublimeDiscordRP#44]
Excerpt from V documentation,

> V is a statically typed compiled programming language designed for building maintainable software.
> It's similar to Go and is also influenced by Oberon, Rust, Swift.
> 
> V is a very simple language. Going through this documentation will take you about half an hour, and by the end of it you will learn pretty much the entire language.
> 
> Despite being simple, it gives a lot of power to the developer. Anything you can do in other languages, you can do in V.

Relevant icons:
<img width="200" alt="v" src="https://user-images.githubusercontent.com/11957313/65856267-bbaebf00-e393-11e9-9407-431a7fe48402.png">
File extension: .v

**Comment by Snazzah** [comment]
Added in [`cea28fc`](https://github.com/Snazzah/SublimeDiscordRP/commit/cea28fc7952c3372da0bf889b1936a7bfb193c22)
