### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Yolodude25** [Snazzah/SublimeDiscordRP#46]
It will start the rich presence, but won't show information at all.
![discord rich presence](https://i.imgur.com/NnSGfxN.png)

**Comment by DanielRTRD** [comment]
![image](https://user-images.githubusercontent.com/9788214/71749754-a192ea00-2e76-11ea-9f10-384296e8fa16.png)
I am having the almost the same issue. It works for a split second then stops.

**Comment by DanielRTRD** [comment]
And I have tried re-installing.

**Comment by DanielRTRD** [comment]
Rebooting after re-install seemed to do the trick.
