### ISSUE TITLE
[Suggestion/Ideia] Others icon's

### ISSUE THREAD

**Issue by SooomS** [Snazzah/SublimeDiscordRP#47]
Hi, first just want to say that I love your code, and works amazing. And i want to ask if it's possible to add more icons for others languages. 

I use Pawn (its used for sa:mp(gaming)) and Processing for example, and maybe you could put a icon for others languages that people use, or you could add a little file that people can edit and insert himself.

I don't know if it's possible, but it's only a suggestion. ^^

Thanks and keep the good work.

**Comment by dmsass** [comment]
Good idea to complement programming language icons

**Comment by Snazzah** [comment]
If you have icons for the programming langs I can add them to the application.

**Comment by SooomS** [comment]
I dont know if you need a especif size, but i am gonna send one on a bigger size and other in small size. I am only sending for processing and pawn, because it's the languages that i use.

![Pawn_big](https://user-images.githubusercontent.com/42103361/80317835-0c897780-87fe-11ea-9c10-f3b5cd4f29e9.png)
![Pawn_small](https://user-images.githubusercontent.com/42103361/80317836-0d220e00-87fe-11ea-9216-3bae26c5fc05.png)

![processing_small](https://user-images.githubusercontent.com/42103361/80317843-16ab7600-87fe-11ea-8977-759a81fdbfc4.png)
![processing_big](https://user-images.githubusercontent.com/42103361/80317844-17440c80-87fe-11ea-90bf-491a5e85a7ee.png)

**Comment by Snazzah** [comment]
I am not too sure for the pawn icon, but I can definitely add processing. Do you know the extension (or whatever to put in `AVAILABLES_ICONS`)?

**Comment by SooomS** [comment]
> I am not too sure for the pawn icon, but I can definitely add processing. Do you know the extension (or whatever to put in `AVAILABLES_ICONS`)?

The extension for processing is .pde and the Pawn is .pwn
