### ISSUE TITLE
Poor display quality of the main icon {Sublime Text 3}

### ISSUE THREAD

**Issue by Calvin-rgb** [Snazzah/SublimeDiscordRP#48]
Perhaps this is a problem in my display, but it seems to me that the main editor icon in discord loses the clarity of the image, apparently due to the small resolution of the picture. If so, then I suggest replacing the icon with a higher resolution.
What it looks like now:
![image](https://user-images.githubusercontent.com/52075975/79148120-377fce80-7def-11ea-90fb-757810e9177d.png)

For instance:
![image](https://user-images.githubusercontent.com/52075975/79148059-1cad5a00-7def-11ea-85dd-595282f93c1b.png)

**Comment by SirNapkin1334** [comment]
I agree. Additionally, it just feels slightly off - I feel like the S is a bit too small in the current version.

**Comment by Snazzah** [comment]
Replaced the icon. Thanks for the image!
