### ISSUE TITLE
Not displaying details/state on my profile

### ISSUE THREAD

**Issue by Jric0** [Snazzah/SublimeDiscordRP#5]
Profile: https://i.imgur.com/yG3DesE.png

Discord Console: https://i.imgur.com/7sAEYKe.png

Sublime Console: https://i.imgur.com/7c4sp3R.png

**Comment by FichteFoll** [comment]
It looks like your "project_name" setting is not a list.

**Comment by Jric0** [comment]
well, @FichteFoll, i haven't edited anything so i don't know where to look to try and fix.

**Comment by FichteFoll** [comment]
Hm. It may be None then, in case the settings haven't been loaded yet. Does the display change when you edit or save a file?

**Comment by Jric0** [comment]
it didn't, but i installed it again and it works now so uh, problem solved.
