### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jackowski626** [Snazzah/SublimeDiscordRP#50]
When this plugin is installed on latest sublime version, the CPU usage can go up to 20%. Any ideas?

**Comment by FichteFoll** [comment]
Can you paste the results of the "Profile Events" command after such high CPU usage? We don't do any demanding computations and retry loops are slowed down by sleeps. Are you sure it doesn't occur without the package?

**Comment by jackowski626** [comment]
Ok, reinstalled the package and it seems to be going fine now. If I ever notice something weird, I'll think about the profile events cmd
