### ISSUE TITLE
SQF Icon

### ISSUE THREAD

**Issue by Sharywan** [Snazzah/SublimeDiscordRP#52]
Hello, I use your plugin a lot but the language I am programming on is not in your plugin.
Could you add it?

if yes this is the SQF of Arma and `* .sqf` for files
Here is the [image](https://arma3.com/assets/img/logos/arma3.png)

Thank you in advance !

**Comment by Snazzah** [comment]
This seems a bit too niche to add as an icon, especially since I have a limited amount of icon slots to use. Sorry.
