### ISSUE TITLE
Doesn't work with OmniSharp

### ISSUE THREAD

**Issue by ezmicken** [Snazzah/SublimeDiscordRP#53]
The package worked once while I was editing the settings for it and hasn't worked since.
When Discord Rich Presence package and OmniSharpSublime package are installed together neither works.

**Comment by Snazzah** [comment]
This needs more clarification

**Comment by ezmicken** [comment]
I removed OmniSharp package and it started to work.
However I looked at the logs closer and i think OmniSharp was the culprit because it was timing out local network requests. Sorry!
