### ISSUE TITLE
Add EJS support

### ISSUE THREAD

**Issue by Waiit** [Snazzah/SublimeDiscordRP#57]
### File extension: 
`.ejs`
### Icon:
[EJS Icon](https://pbs.twimg.com/profile_images/833789473376854018/skScegH6_400x400.jpg)
![Icon for EJS](https://pbs.twimg.com/profile_images/833789473376854018/skScegH6_400x400.jpg)

**Comment by TorchedSammy** [comment]
here's one i think would fit nicely as well  
![](https://modeus.is-inside.me/zfmfdnXG.png)
