### ISSUE TITLE
Add SourcePawn support

### ISSUE THREAD

**Issue by Zabaniya001** [Snazzah/SublimeDiscordRP#60]
**Language:** SourcePawn
**Extension:** sp
**Image:** The image is up to you. You can either utilize the sourcemod icon or a modernized pawn.

 Ex ( it's 512x512 ):
![lang-sp](https://user-images.githubusercontent.com/73082112/98483089-fe350300-2205-11eb-86ee-a5ca9c728e3b.png)

**Comment by TorchedSammy** [comment]
[isn't this the same thing?](https://github.com/Snazzah/SublimeDiscordRP/blob/master/icons/lang-pawn.png)
if so there's already support.

**Comment by Zabaniya001** [comment]
Kinda. It's based on pawn, more specifically it's what sourcemod ( which allows you to make plugins and such for source games ex: csgo, tf2 etc.. ) utilizes. And nope, it doesn't support it. You just get a ? sign instead. You could just add the extension to pawn if you want. Wouldn't be a problem
![Discord_5xJS7kSKiy](https://user-images.githubusercontent.com/73082112/98484470-fa0de300-220f-11eb-82c2-22ae55ff71d8.png)

**Comment by Snazzah** [comment]
I'd rather just tack this on with the pawn icon we already have.
