### ISSUE TITLE
Add TeX/LaTeX icon

### ISSUE THREAD

**Issue by datsuka-qwerty** [Snazzah/SublimeDiscordRP#62]
Thanks for the great package  : )  
Could you please add Tex and LaTeX icon?  

[Like this](https://worldvectorlogo.com/logo/latex)
<img src="https://user-images.githubusercontent.com/49899602/103332150-553fb180-4aac-11eb-8d6f-55f6a647a243.jpg" width="300">

**Comment by Snazzah** [comment]
Can you give me the extensions that this is for?

**Comment by FichteFoll** [comment]
I would guess `.tex` and `.bib`, for starters.
