### ISSUE TITLE
Cython extension please

### ISSUE THREAD

**Issue by Exainz** [Snazzah/SublimeDiscordRP#64]
**Language: Cython**
**Extension(s): pyx**
Image (512x512): 
![lang-cython](https://user-images.githubusercontent.com/72621339/106433900-d1a42680-6496-11eb-8f09-f9d9bfa13acc.png)

**Comment by Exainz** [comment]
A much better one :D
![img](https://user-images.githubusercontent.com/72621339/106503455-a861b580-64eb-11eb-8268-cb6c39fa37af.png)

**Comment by Snazzah** [comment]
Don't think it would be all that necessary to add a new icon for an extension to Python, so I've added `pyx` to the `python` key instead.
