### ISSUE TITLE
Question: How do I add a custom file extension rich presence?

### ISSUE THREAD

**Issue by Exainz** [Snazzah/SublimeDiscordRP#65]
I tried editing the drp.py file and adding the file extension to it like `.exainz`,  and pasted the logo into the folder with name `lang-exainz.png`.
But the image didnt load up 
Thanks

**Comment by TorchedSammy** [comment]
To actually add the icon, you need to add it to the Discord application at the developer portal, but only @Snazzah has access.

Which means you'd have to make your own app and add the ID of that app to `drp.py`, and add all icons (custom included) to the app.

This is why to add a new icon, it's requested via an issue.
