### ISSUE TITLE
Presence state stuck on discord profile, time counter still going, which can't be stopped until you restart and blocks other "Presences"

### ISSUE THREAD

**Issue by VXsz** [Snazzah/SublimeDiscordRP#66]
So sometimes for some reason, the state freezes to "Just launched" and stays like that forever but the timer is still going, so far this happened a couple of times and the counter goes for days still counting time until I restart windows

![image](https://user-images.githubusercontent.com/34054757/108547935-32878780-72fc-11eb-8d8c-4aac6c1f4891.png)
(in the above image, the presence actually is 34 hrs because it restarts the counter every 24hrs)

**it's pretty annoying** because I have a couple stuff that I need to run 24/7 and can't restart everytime, and so far it have been a %50 to get this problem whenever I use/launch Sublime

Also I tried searching on task manager to find the service (that runs the rich presence) and terminate it but couldn't find it

**Comment by TorchedSammy** [comment]
A similar thing has happened to me on osu before, which I think is a problem of Discord itself and not the rich presence
Also, no need to completely reopen Discord or restart Windows, a good ctrl+r on Discord should remove it

**Comment by TorchedSammy** [comment]
Does it not change the presence at all when you edit?

**Comment by VXsz** [comment]
> 
> 
> Does it not change the presence at all when you edit? Can you post some logs (set the plugin's log level to `WARNING` or `DEBUG`)

I tried refreshing discord and it worked, that's so much better 

when this happens I usually just continue coding, but after it errors out it **never** changes state, even if I code for like 12hrs straight, next time I code I will make sure it captures the log since I'm on my weekend now, unless it stores logs
