### ISSUE TITLE
Only newly opened tabs are displayed

### ISSUE THREAD

**Issue by s-clerc** [Snazzah/SublimeDiscordRP#69]
I'm on build 4099 on a Mac. The issue is that the extension ignores any tabs that were opened when ST started up, and only recognises newly opened tabs.

This includes tabs opened after the extension was installed, they are ignored if I quit and then open ST.

**Comment by TorchedSammy** [comment]
simply saving the file should update it

**Comment by Snazzah** [comment]
This isn't really too much of a problem and should update once you save/type in a file, hence the "Just Launched" and "Idle" texts.
