### ISSUE TITLE
Fix the update Rich Presence.

### ISSUE THREAD

**Issue by DoctorVWA** [Snazzah/SublimeDiscordRP#7]
Update the Rich Presence for the selected file, It only updates when I save the file.

Edit 1:
you can use 15 seconds in the if what checks the time passed to change, you are using 59.

**Comment by FichteFoll** [comment]
Why so you think 59 is not enough?

**Comment by DoctorVWA** [comment]
~~I live on the limits~~

I think more updates can show more things, sometimes in one minute eu switch and edit more than one file...

**Comment by gwenzek** [comment]
It could be a settings I guess. For me 1 minute seems fine, and 15s a bit overkill given that I only send the project name,

**Comment by FichteFoll** [comment]
As mentioned in #9, this shouldn't be an issue.
