### ISSUE TITLE
Sometimes the rich presents goes away

### ISSUE THREAD

**Issue by OreoDivision** [Snazzah/SublimeDiscordRP#70]
It randomly goes away, one I restart sublime it work again, saving won’t help.

**Comment by Snazzah** [comment]
I need more information than this. The only possibility that could do this is if your Discord stops working or closes the IPC, which you can re-establish with a command. (Ctrl+Shift+P)

![](https://get.snaz.in/3bVgwE9.png)

**Comment by OreoDivision** [comment]
So, When I either go AFK or open 2 or more Sublime Texts, it breaks, I have to close the sublime or save the file to start it again, ill try and see a pattern

**Comment by OreoDivision** [comment]
And can you have AFK optional ? @Snazzah

**Comment by Snazzah** [comment]
AFK is not optional, and this may have been fixed with 66d30eddbd595ff6e1e6ce6e67df31c14c440475 or a87bd37f61665573b5f6f29c903dc779492b5c94.

**Comment by OreoDivision** [comment]
Okay, thx
