### ISSUE TITLE
Unsolicited infinite freezes

### ISSUE THREAD

**Issue by Medallyon** [Snazzah/SublimeDiscordRP#71]
I've long been wondering (a few months) why my ST3 was randomly freezing, indefinitely unresponsive, and eventually have to manually quit out via Task Manager. I finally had enough and chose to track down the issue by systematically disabling and re-enabling my packages one by one. It seems as though this is the only package where this behaviour with ST3 occurs.

I don't think it's completely random. I've noticed that most often, it happens when I close a tab, either with an `MMB` click or `CTRL`+`W`.

My setup is as follows:

+ Windows 10 Pro (Update 20H2)
+ Sublime Text 3 v3211
  + I usually have 3+ different project folders added to the project pane, if that's of any relevance
+ Packages
  + SFTP
  + SublimeLinter (with SublimeLinter-eslint)

I love this package to bits and I want to do more to fix this. If you have any idea about any logs I can submit that would help, or anything else for that matter, please let me know.

**Comment by Snazzah** [comment]
Not sure where this is coming about. I've been using it recently in a project and haven't gotten any issues while closing tabs. You can open the console with <kbd>ctrl</kbd>+ <kbd>`</kbd>, or open Discord's console with the instructions below, not too sure how to fix this if there is a problem. Might be something holding up the IPC.

---
<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd> to open Discord's Console (<kbd>option</kbd> + <kbd>cmd</kbd> + <kbd>i</kbd> on mac)

**Comment by FichteFoll** [comment]
I could see the following `on_close` event handler causing at least smaller freezes since it is the only blocking call, but I wouldn't expect it to freeze indefinitely. 

https://github.com/Snazzah/SublimeDiscordRP/blob/61755f229c8b1acfca6fedb3e70a9f1acfacc420/drp.py#L333-L339

@Snazzah, when is the condition expected to trigger? When all views of a window have been closed?

**Comment by Snazzah** [comment]
@FichteFoll Yes, but I need to fix this. At the moment, it just goes back to the idle presence when it is closed.

**Comment by Medallyon** [comment]
I've been using 66d30eddbd595ff6e1e6ce6e67df31c14c440475 since the last comment and I have not gotten any freezes as described.
