### ISSUE TITLE
Add option to disable time.

### ISSUE THREAD

**Issue by jkelol111** [Snazzah/SublimeDiscordRP#72]
If it's possible, an option should be added to allow for disabling the time completely on the Rich Presence. (a.k.a only details and state)

**Comment by MestoDan** [comment]
@jkelol111 Go to: 
Preferences -> Package Settings -> Discord Rich Presence -> Settings. Then you need to find `"time_per_file": true` => `"time_per_file": false` -> Reload Sublime Text
