### ISSUE TITLE
DiscordRP stopped working after the new update

### ISSUE THREAD

**Issue by 0jxf** [Snazzah/SublimeDiscordRP#73]
Hello, so i'm not really sure if it's from the update because it was working before and stopped working after i updated discord.
I tried reinstalling the package from sublime package installer and GitHub but still it doesn't seem to work. Even tried it on my friend have the same issue.

When i try connecting the package to discord i get this error.

![image](https://user-images.githubusercontent.com/54437675/121786872-f2a62200-cbc2-11eb-9da9-e67a1ff96807.png)

any ideas?

**Comment by Snazzah** [comment]
Can you Copy Paste what Discord says about IPC in the Console?

---
<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd> to open Discord's Console (<kbd>option</kbd> + <kbd>cmd</kbd> + <kbd>i</kbd> on mac)

**Comment by 0jxf** [comment]
I don't get any outputs from Discord IPC just normal Discord activity like

![image](https://user-images.githubusercontent.com/54437675/121931311-bfd76780-cd43-11eb-990e-996ad3d64e1c.png)

**Comment by Snazzah** [comment]
Could you set the "log_level" to "DEBUG" in the packages preferences and open Sublime's logs with <kbd>Ctrl</kbd> + <kbd>`</kbd>?

**Comment by 0jxf** [comment]
Apparently there's no such file or directory
> [Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 13] Permission denied: '\\\\?\\pipe\\discord-ipc-0'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 13] Permission denied: '\\\\?\\pipe\\discord-ipc-0'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'

**Comment by 0jxf** [comment]
Well when i read `[Discord Rich Presence.discord_ipc] ERROR: failed to open '\\?\pipe\discord-ipc-0': [Errno 13] Permission denied: '\\?\pipe\discord-ipc-0'`
I tried to open sublime text as administrator and it worked.
My bad it's working now
