### ISSUE TITLE
Need help on setup

### ISSUE THREAD

**Issue by Copimox** [Snazzah/SublimeDiscordRP#76]
This isn't an issue but after installing Package Control on Sublime Text I can't figure out how to install SublimeDiscord
Please help

**Comment by Snazzah** [comment]
![image](https://camo.githubusercontent.com/ff3df50a4bad4b83b2072550c1d8cf6f5d55d159/68747470733a2f2f692e696d6775722e636f6d2f737a7475474f572e676966)
