### ISSUE TITLE
Add missing icons from fileicon's repo

### ISSUE THREAD

**Issue by siddhpant** [Snazzah/SublimeDiscordRP#77]
The file icon package also has icons which show up besides filename and is very widely used.

Understandably, they have a larger assortment of icons, which can be found on https://github.com/SublimeText/AFileIcon/tree/master/icons/svg.

We can add icons which this one lacks from there.

**Comment by Snazzah** [comment]
This a bit stale so I'll close this. As far as importing all of these, I'll go through some of them late, but some of them I don't have extensions to go by.
