### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Spinayy** [Snazzah/SublimeDiscordRP#83]
It just gives me this error. I have tried everything..

https://prnt.sc/25fzqry

**Comment by Snazzah** [comment]
Can you Copy Paste what Discord says about IPC in the Console?

---
<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd> to open Discord's Console (<kbd>option</kbd> + <kbd>cmd</kbd> + <kbd>i</kbd> on mac)
