### ISSUE TITLE
shortcut to enable/stop the presence

### ISSUE THREAD

**Issue by pi141** [Snazzah/SublimeDiscordRP#90]
a customizable shortcut to enable/stop the rich presence

**Comment by FichteFoll** [comment]
You can create custom key bindings for these commands like you would for any other plugin.

https://github.com/Snazzah/SublimeDiscordRP/blob/21fd33f5669c79ed7833d1650cc4a64088a7d6ad/Default.sublime-commands#L10-L21

**Comment by pi141** [comment]
thanks!
